---
name: Demo of env vars
on:
  - push
  - pull_request
jobs:
  demo:
    name: Demo job
    strategy:
      matrix:
        include:
          - demo_bool: true
          - demo_bool: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run script
        run: |
          source ${{ github.workspace}}/demo.sh
        env:
          DEMO_VAR: "hello, world"
          DEMO_BOOL: ${{ matrix.demo_bool }}
